app = "worldcal-wikipedia-spider"
primary_region = "ams"
swap_size_mb = 512

[build]
  image = "registry.fly.io/worldcal-wikipedia-spider:latest"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
