services:
  db:
    image: postgres
    hostname: db
    restart: always
    shm_size: 128mb
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: example
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    networks:
      - postgres

  minio:
    image: quay.io/minio/minio:latest
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: ACCESSKEY
      MINIO_SECRET_KEY: SECRETKEY

      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123

  pgadmin:
    image: dpage/pgadmin4
    hostname: pgadmin
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - ./data/pgadmin:/var/lib/pgadmin
    network_mode: host
    depends_on:
      - db

  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data/neo4j:/data
    environment:
      - NEO4J_AUTH=neo4j/mypassword
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]

  # typesense:
  #   image: typesense/typesense:26.0
  #   restart: on-failure
  #   ports:
  #     - "8108:8108"
  #   volumes:
  #     - ./data/typesense-data:/data
  #   command: '--data-dir /data --api-key=xyz --enable-cors'

networks:
  postgres:
    driver: bridge
