app = "worldcal-web"
primary_region = "ams"

swap_size_mb = 512

[build]
  image = "registry.fly.io/worldcal-web:latest"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
