name: Deploy Calendar Index

on:
  push:
    branches:
      - master

jobs:
    deploy_muncher:
      name: Deploy muncher
      runs-on: ubuntu-latest
      concurrency: deploy-group    # optional: ensure only one action runs at a time

      # run if the directory changes
      if: ${{ github.event_path == 'calendar_index/muncher' }}

      env:
        FLY_APP: worldcal-muncher

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - uses: superfly/flyctl-actions/setup-flyctl@master
          with:
            version: latest

        - run: flyctl auth docker
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            push: true
            context: ./calendar_index
            file: ./calendar_index/Dockerfile
            build-args: |-
              APP=muncher
            tags: registry.fly.io/${{ env.FLY_APP }}:latest

        - run: flyctl deploy
          working-directory: ./calendar_index/muncher
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    deploy_spider:
      name: Deploy Spider
      runs-on: ubuntu-latest
      concurrency: deploy-group    # optional: ensure only one action runs at a time

      # run if the directory changes
      if: ${{ github.event_path == 'calendar_index/spider' }}

      env:
        FLY_APP: worldcal-spider

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - uses: superfly/flyctl-actions/setup-flyctl@master
          with:
            version: latest

        - run: flyctl auth docker
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            push: true
            context: ./calendar_index
            file: ./calendar_index/Dockerfile
            build-args: |-
              APP=spider
            tags: registry.fly.io/${{ env.FLY_APP }}:latest

        - run: flyctl deploy
          working-directory: ./calendar_index/spider
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
