name: Deploy Calendar Index

on:
  push:
    branches:
      - master

jobs:
  changes:
    name: Detect changes
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      spider: ${{ steps.filter.outputs.spider }}
      muncher: ${{ steps.filter.outputs.muncher }}
      critiquer: ${{ steps.filter.outputs.critiquer }}
      wikipedia_spider: ${{ steps.filter.outputs.wikipedia_spider }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
            spider:
              - 'calendar_index/start.sh'
              - 'calendar_index/spider/**'
              - 'calendar_index/Dockerfile'
              - 'calendar_index/poetry.lock'
              - 'calendar_index/pyproject.toml'
            muncher:
              - 'calendar_index/start.sh'
              - 'calendar_index/muncher/**'
              - 'calendar_index/Dockerfile'
              - 'calendar_index/poetry.lock'
              - 'calendar_index/pyproject.toml'
            critiquer:
              - 'calendar_index/start.sh'
              - 'calendar_index/critiquer/**'
              - 'calendar_index/Dockerfile'
              - 'calendar_index/poetry.lock'
              - 'calendar_index/pyproject.toml'
            wikipedia_spider:
              - 'calendar_index/start.sh'
              - 'calendar_index/Dockerfile'
              - 'calendar_index/poetry.lock'
              - 'calendar_index/pyproject.toml'
              - 'calendar_index/wikipedia_spider/**'
  
              
  deploy_muncher:
    name: Deploy muncher
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time

    # run if the directory changes
    needs: changes
    if: ${{ needs.changes.outputs.muncher == 'true' }}

    env:
      FLY_APP: worldcal-muncher

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: superfly/flyctl-actions/setup-flyctl@master
      with:
        version: latest

    - run: flyctl auth docker
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        context: ./calendar_index
        file: ./calendar_index/Dockerfile
        build-args: |-
            APP=muncher
        tags: registry.fly.io/${{ env.FLY_APP }}:latest

    - run: flyctl deploy
      working-directory: ./calendar_index/muncher
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy_spider:
    name: Deploy Spider
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time

    # run if the directory changes
    needs: changes
    if: ${{ needs.changes.outputs.spider == 'true' }}

    env:
      FLY_APP: worldcal-spider

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: latest

      - run: flyctl auth docker
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./calendar_index
          file: ./calendar_index/Dockerfile
          build-args: |-
            APP=spider
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: registry.fly.io/${{ env.FLY_APP }}:latest

      - run: flyctl deploy
        working-directory: ./calendar_index/spider
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy_critiquer:
    name: Deploy Critiquer
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time

    # run if the directory changes
    needs: changes
    if: ${{ needs.changes.outputs.critiquer == 'true' }}

    env:
      FLY_APP: worldcal-critiquer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: latest

      - run: flyctl auth docker
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./calendar_index
          file: ./calendar_index/Dockerfile
          build-args: |-
            APP=critiquer
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: registry.fly.io/${{ env.FLY_APP }}:latest

      - run: flyctl deploy
        working-directory: ./calendar_index/critiquer
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy_wikipedia_spider:
    name: Deploy Wikipedia Spider
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time

    # run if the directory changes
    needs: changes
    if: ${{ needs.changes.outputs.wikipedia_spider == 'true' }}

    env:
      FLY_APP: worldcal-wikipedia-spider

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: latest

      - run: flyctl auth docker
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./calendar_index
          file: ./calendar_index/Dockerfile
          build-args: |-
            APP=wikipedia_spider
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: registry.fly.io/${{ env.FLY_APP }}:latest

      - run: flyctl deploy
        working-directory: ./calendar_index/wikipedia_spider
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
